### PR TITLE
Fixes #63: Implement Customizable Model Selection

### LINKED ISSUE #63: Make model customizable
Default model should be anthropic (will require updates, atm default is openai)
If user wants a diff model, require api key

### PR DESCRIPTION
**Pull request by ahmad2b**
This PR implements flexible model selection system, allowing users to switch between OpenAI and Anthropic models while maintaining a consistent user experience. 

{D39CA9A4-8E66-4BC1-BAC1-7651FDB4BEE3}

Key technical aspects:
- **Model Selection Pattern**: New abstraction layer in `lib.ts` that provides uniform interface for different AI models
- **Type-Safe Integration**: Strict typing for model names and configurations using TypeScript literal types
- **Stateful Model Management**: Thread-level model persistence with automatic state handling
- **Seamless UX**: ChatGPT-style model switching with automatic thread management

https://github.com/user-attachments/assets/5d7653f3-e0ff-462b-a914-24bcd0f54329

### New Files
* `src/agent/lib.ts` - Core model abstraction and selection implementation

#### Core Changes
- `src/open-canvas/index.ts`, `src/agent/open-canvas/state.ts`
  - Added model state management and type definitions

- Updated model implementation across agent nodes in `src/agent/open-canvas/nodes/*`
  - Refactored chat model initialization using new pattern

#### UI/UX Updates
* New `ModelSelector.tsx` component
* Updated hooks (`useGraph.tsx`, `useThread.tsx`) with model state support
* Updated canvas and primitives components for model integration

## Testing
Tested with:
- Anthropic API integration
- OpenAI API integration
- Verified model switching functionality
- Thread preservation and recreation

Please let me know if any changes or additional information is needed.

Fixes #63

### CODE REVIEW

**Review by bracesproul — CHANGES_REQUESTED** [review]
Thanks for putting an initial PR up @ahmad2b! I should've written a better spec in the github issues though, as this needs some changes I'll outline below

We already have an [`initChatModel` class in the `langchain` library which can do this](https://v03.api.js.langchain.com/functions/langchain.chat_models_universal.initChatModel.html). You should use that function instead. As for the models, we should offer:

`gpt-4o-mini` from OpenAI
`claude-3-haiku-20240307` from Anthropic
`accounts/fireworks/models/llama-v3p1-70b-instruct` and `accounts/fireworks/models/llama-v3p1-8b-instruct` from Fireworks

These models should only be used in places where `gpt-4o-mini` is used now (there are some nodes which require better models `updateArtifact`, `updateHighlightedText` and the reflection graph. These should not change).

Additionally, the model name shouldn't be stored in state, but rather passed in via the configurable fields

you can access it in nodes via `config.configurable`, and pass to the API like this:
```typescript
const stream = client.runs.stream(
  useGraphInput.threadId,
  useGraphInput.assistantId,
  {
    input,
    streamMode: "events",
    // here
    config: {
      configurable: {
        customModelName: "..."
      }
    }
  }
);
```

Lastly, we shouldn't change the model for any requests which use tool calling since those can stream back the data in different formats, and would require a fair amount of refactoring to handle clientside.

Super sorry I didn't spec this out better beforehand, and if you're not up for changing to this spec that's all good.

Thanks again for making a start on this!

**Comment by ahmad2b** [comment]
Thank you @bracesproul for the detailed review! I appreciate the clear guidance. I’ll revise the PR to:

- Utilize the existing initChatModel class from Langchain
- Add support for the specified models
- Move model selection to configurable fields instead of state
- Keep the original models for tool-calling nodes

No worries about the spec; I’m excited to implement these changes and will push the updates soon. Thanks again!

**Comment by bracesproul** [comment]
Great! Very excited to review again once ready. Please just dismiss my change request review & re-request. Thanks!

**Comment by ahmad2b** [comment]
Hi @bracesproul! I’ve created a new PR (#136 ) for the requested changes to avoid conflicts with the main branch, as the main branch had substantial updates that would make merging challenging. All changes and improvements are now reflected there. Closing this PR to keep everything organized. Thank you for the guidance!

**Pull request closed without merging**
