### PR TITLE
feat: Update markdown editor to render md live in editor

### PR DESCRIPTION
**Pull request by liuhuapiaoyuan**
image

Can switch between preview/edit mode

### CODE REVIEW

**Review by bracesproul — CHANGES_REQUESTED** [review]
Hey @liuhuapiaoyuan what we're looking for here is instead to have a single view where users can edit and view the rendered markdown, like in Notion (included video below). What you put up is a little different, where it displays the editing and viewing state at the same time.

https://www.loom.com/share/e30a816d9391450e925f67c7a47125db?sid=c6c0c8a9-77b2-4765-ba32-05989f51b79a

**Comment by liuhuapiaoyuan** [comment]
> Hey @liuhuapiaoyuan what we're looking for here is instead to have a single view where users can edit and view the rendered markdown, like in Notion (included video below). What you put up is a little different, where it displays the editing and viewing state at the same time.
> 
> https://www.loom.com/share/e30a816d9391450e925f67c7a47125db?sid=c6c0c8a9-77b2-4765-ba32-05989f51b79a

You can try : https://templates.tiptap.dev/TFcjrd9thK

**Comment by bracesproul** [comment]
@liuhuapiaoyuan yes that would work!!

**Comment by liuhuapiaoyuan** [comment]
@liuhuapiaoyuan yes that would work!!

I am going to implement this feature, is that okay?

**Comment by bracesproul** [comment]
Closing in favor of #65

**Pull request closed without merging**
