### PR TITLE
@liuhuapiaoyuan feat: Update markdown editor to render md live in editor

### PR DESCRIPTION
**Pull request by liuhuapiaoyuan**

### CODE REVIEW

**Comment by liuhuapiaoyuan** [comment]
f18322f33a6dc6899062de76df01ca5

**Comment by liuhuapiaoyuan** [comment]
TODO: 

- [ ] I will resolve the highlight positioning error issue caused by markdown symbols

**Comment by bracesproul** [comment]
@liuhuapiaoyuan I pushed up some commits getting it to work, and ended up refactoring a large amount of the artifacts code 😅. Don't worry about making any more changes, I'll be pushing up some more commits cleaning it all up, and once done I'll merge into `staging`.

Thank you again for getting this started, it's very appreichated!

Side note, do you have a twitter? Would love to tag you as a contributor when I announce this new feature!

**Comment by liuhuapiaoyuan** [comment]
Thank you. Of couse,this project is so cool!  

[https://x.com/liuhuapiaoyuan](https://x.com/liuhuapiaoyuan)

I also have this idea, to make change submissions through titap/section capabilities

You can drop useEffect ,  tipta provider a listener:
image

**Comment by liuhuapiaoyuan** [comment]
If you're up for it, I can keep refining it based on your suggestions

**Pull request merged**
